/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#004c25",
        "primary-container": "#006634",
        "on-primary": "#ffffff",
        "on-primary-container": "#8ce1a2",
        "primary-fixed": "#9ff5b5",
        "primary-fixed-dim": "#84d99a",
        "on-primary-fixed": "#00210d",
        "on-primary-fixed-variant": "#005229",
        secondary: "#506354",
        "on-secondary": "#ffffff",
        "secondary-container": "#d2e8d5",
        "on-secondary-container": "#55695a",
        "secondary-fixed": "#d2e8d5",
        "secondary-fixed-dim": "#b6ccba",
        "on-secondary-fixed": "#0d1f14",
        "on-secondary-fixed-variant": "#384b3d",
        tertiary: "#742531",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#923c47",
        "on-tertiary-container": "#ffbfc3",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#f6fbf3",
        "surface-dim": "#d7dbd4",
        "surface-bright": "#f6fbf3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f5ed",
        "surface-container": "#ebefe8",
        "surface-container-high": "#e5e9e2",
        "surface-container-highest": "#dfe4dc",
        "on-surface": "#181d18",
        "on-surface-variant": "#3f4940",
        "inverse-surface": "#2d322d",
        "inverse-on-surface": "#eef2eb",
        outline: "#6f7a6f",
        "outline-variant": "#bfc9bd",
        "surface-tint": "#0f6d3a",
        background: "#f6fbf3",
        "on-background": "#181d18",
        "surface-variant": "#dfe4dc",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        heading: ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "body-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "14px", fontWeight: "600" }],
      },
      spacing: {
        base: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        gutter: "16px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
